### ISSUE TITLE
Best lists management

### ISSUE THREAD

**Issue by lgasnier** [gmr/flatdict#11]
1. List order is not kept when list is flattened and then returned as a dictionary with *as_dict()* if the length of the list is more than 10.
For example:
  ```
  In [1]: values = {'foo': list(range(11))}
  In [2]: flatdict.FlatDict(values).as_dict()
  Out [2]: {'foo': [0, 1, 10, 2, 3, 4, 5, 6, 7, 8, 9]}
  ```
2. A list of tuples (or lists) is not restored by *as_dict()*.
For example:
  ```
  In [1]: values = {'foo': [(1, 2, 3), (10, 20, 30)]}
  In [2]: flatdict.FlatDict(values).as_dict()
  Out [2]: {'foo': [1, 2, 3, 10, 20, 30]}
  ```
The diff attach file  [diff-flatdict.txt](https://github.com/gmr/flatdict/files/949787/diff-flatdict.txt) proposes code changes for these issues and an enhancement to control if lists and tuples are flattened (parameter *dict_only=False*, default value) or not (*dict_only=True*). For example:
  ```
  In [1]: values = {'foo': [(1, 2, 3), (10, 20, 30)],
                    'bar': {'baz': 4, 'qux': 5}}
  In [2]: flatdict_new.FlatDict(values, dict_only=True)
  Out [2]: {'bar:baz': 4, 'foo': [(1, 2, 3), (10, 20, 30)], 'bar:qux': 5}
  ```

**Comment by gmr** [comment]
I ended up breaking out the list/tuple functionality that is in a new class (FlatterDict). In the rewrite of that functionality, the original order should be maintained.

Thanks for the patch and the report.
