### ISSUE TITLE
all values are transed to str?

### ISSUE THREAD

**Issue by KeithTt** [gmr/flatdict#23]
In my source dict, values are numbers, how to remain the value type?

```
source = {
    'a':{
        'b':1,
        'c':2
        },
    'd':{
        'e':3,
        'f':{
            'g':4
            }
        }
}

target = flatdict.FlatDict(source, delimiter='.')
print(target)
# {'a.b': '1', 'a.c': '2', 'd.e': '3', 'd.f.g': '4'}
```

**Comment by gmr** [comment]
In this case, you're printing so the values are outputted as strings. I've updated repr and str methods to not coerce output to string for 3.1. There is no assignment coercion taking place in the version you're using other than for printing/string cast methods.
