### ISSUE TITLE
FlatDict flattens empty dictionary as FlatDict object rather than {}

### ISSUE THREAD

**Issue by devleaks** [gmr/flatdict#48]
```
>>> import flatdict
>>> print(flatdict.FlatDict({"test": {}}))
{'test': <FlatDict id=140555892896048 {}>"}
```
Empty dict {} does not get flattened as {} but remains as FlatDict object.
(Same with FlatterDict.)
P.

**Comment by gmr** [comment]
This is expected behavior. You'd need to coerce it to a dict for it to be a dict, it's part of the core behavior.
