### ISSUE TITLE
Issue installing with pipenv

### ISSUE THREAD

**Issue by Dan-Gelderd** [gmr/flatdict#58]
I was having issues with my pip-lock after running pipenv install flatdict.
In the pipefile, the dependency was listed as:
flatdictpipenv = "*"

I manually corrected to 
flatdict = "*"

and things seem to have worked.

Sorry if this is just me doing something daft.

**Comment by gmr** [comment]
I don't use pipenv, so I can't speak to how it should function.  The package name is `flatdict` so your correction looks more correct to me than `flatdictpipenv`.
