### ISSUE TITLE
Check for list

### ISSUE THREAD

**Issue by glenncoppens** [gmr/flatdict#7]
Hi

I have this use case where I know a certain key to check against, but I don't know yet if the value for that key is going to be a list or not (a simple string, int,...). 

So I was thinking if there could be an easy way to check whether a key will be a list, so I can get all the items in the list by iterating over the key and appending ":0", ..., ":n"

Tnx :)

**Comment by gmr** [comment]
Not sure I follow, sorry. Closing due to age. If still interested, please provide a snipped of Python code that shows what you would like to be able to do.
